### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by davidbaniadam** [rnuske/komaletter#6]
Hi,
Thanks for the package. 
How can I change the font.. it does not seem to be working?
And the `return-address`show double. How can only keep the upper-left one?

**Comment by rnuske** [comment]
Hi David,
I regarded the font to be a fundamental part of the layout and as such hardcoded it in the default layout [maintainersDelight.lco](https://github.com/rnuske/komaletter/blob/f6dee20f3768cff0219dcc6c4df1cd8de59bfdf7/inst/rmarkdown/templates/pdf/resources/maintainersDelight.lco).  Meaning, a different choice of fonts requires a custom `.lco`-file. One could copy the [maintainersDelight.lco](https://github.com/rnuske/komaletter/blob/f6dee20f3768cff0219dcc6c4df1cd8de59bfdf7/inst/rmarkdown/templates/pdf/resources/maintainersDelight.lco) into the working directory, adapt to one's own taste and reference the custom style-file it with the YAML parameter `lco` in the heading of the letter. 

Looking into the [template](https://github.com/rnuske/komaletter/blob/f6dee20f3768cff0219dcc6c4df1cd8de59bfdf7/inst/rmarkdown/templates/pdf/resources/template.tex) used by pandoc I recognized that `rmarkdown` usually seems to offer the possibility to change the font. I have to think about if and how `komaletter` should support these parameters.

Could you please post a minimal reproducible example showing which YAML header parameters you want to use.

**Comment by rnuske** [comment]
Could you please open a separate issue for the trouble with the `return-address` containing a  minimal reproducible example.

**Comment by davidbaniadam** [comment]
Hi thanks for the response. People like the design with `return-address` so I think I just keep it the way it is. 
So if you want you can just close the issue. 
And I think the font is good too now. 
Again thanks for the package!
All the best

**Comment by rnuske** [comment]
Things I learned while searching for a way to change the font:
 * The default `lco`-settings (`maintainerDelight.lco`) overwrites font choices  done elsewhere because it is loaded later than the options set via YAML and the `template.tex`.
 * I could not find a way to make loading of fonts conditional in default lco `maintainerDelight.lco`. 
   * The `lco` does not know about YAML parameters. All pandoc magic is already done when the `lco` comes into play.
   * Conditioning in LaTeX using e.g. `\usepackage{ifthen}` does not work because there is no easy way to detect whether a custom font was set. Font setting looks very different depending on the YAML parameter given by the user e.g. setting fonts via tex-packages or xelatex and `fontspec`. Maybe set a flag if a custom font is set?


Hacks / Workarounds:
  * an "easy" way out is using a different `lco`-file, e.g.
    * one of the standard lco `lco: DIN` (this allows for setting fonts via YAML parameter `fontfamily`, e.g. `lco: DIN` together with `fontfamily: arev`) [1]
    * or a personal custom lco with a hardcoded favorite font
  * another handy hack would be to overide the font definition in default `lco`-settings `maintainerDelight.lco`) by changing the fontselection method to `fontspec` which requires xelatex. A sans font has to be provided because `maintainerDelight.lco` makes sans font the documents default font, e.g. use `latex_engine: xelatex` together with `sansfont: Arial` [2]


[1]
```
---
author: Max Mustermann
return-address: [Musterstr. 12, 34567 Musterstadt]
address: [Dirk Eddelbuettel, 123 Street Rd, Chicago, IL]

lco: DIN   
fontfamily: arev

output:  komaletter::komaletter
---

```

[2]
```
---
author: Max Mustermann
return-address: [Musterstr. 12, 34567 Musterstadt]
address: [Dirk Eddelbuettel, 123 Street Rd, Chicago, IL]

sansfont: Optima

output: 
  komaletter::komaletter:
    latex_engine: xelatex
---

```

**Comment by rnuske** [comment]
To conclude, I would appreciate suggestions on how to set a font in the default lco that can be overridden by YAML settings.
