### ISSUE TITLE
Not able to knit documents with Rmarkdown anymore

### ISSUE THREAD

**Issue by jrennstich** [rnuske/komaletter#7]
Unfortunately, I am not able to knit documents using RStudio/Rmarkdown using `komaletter` anymore (yields an error, because it calls the `grffile` package, which is now a legacy package (thanks to @cderv for providing this related information caused by this):

> This is related to other questions from a few days ago around the web:
> [https://superuser.com/questions/1500464/unable-to-knit-to-pdf-using-tinytex-missing-sty-file](https://superuser.com/questions/1500464/unable-to-knit-to-pdf-using-tinytex-missing-sty-file)
>     Maybe be this one too: [ho-tex/grffile#1](https://github.com/ho-tex/grffile/issues/1)
> 
> It seems the `grffile` is now a [legacy package](https://www.ctan.org/ctan-ann/id/mailman.1030.1573236486.2586.ctan-ann@ctan.org) and there was change in how this package is required or not.
> 
> It has been removed from pandoc template a week ago [jgm/pandoc@4d5fd9e](https://github.com/jgm/pandoc/commit/4d5fd9e2fe360e47fd5beab724c612ce29aa39ee) with an issue to follow how it evolves. see [jgm/pandoc#5848](https://github.com/jgm/pandoc/issues/5848)

Does anyone know how to work around this? I am trying to meet a deadline and am unable to use my letter templates now... :-(

**Comment by cderv** [comment]
For your deadline as a temporary fix, I think you can fork this repository, and make your own version by modifying this line
https://github.com/rnuske/komaletter/blob/0648c486d0b1c41915aad616b26c094cff794fdd/inst/rmarkdown/templates/pdf/resources/template.tex#L126 
in the template as I suggested for rmarkdown. 

You'll then need to install your forked version because `komaletter` doesn't allow to provide a new template 
https://github.com/rnuske/komaletter/blob/0648c486d0b1c41915aad616b26c094cff794fdd/R/komaletter.R#L99-L110

I hope this should work as it did for rmarkdown while a long term fix is done 
(by modifying this template ?)

**Comment by cderv** [comment]
This has now been fixed in dev version of Rmarkdown. Maybe the same fix should be applied here. 
https://github.com/rstudio/rmarkdown/commit/1f6394313256f6628c12be81784451fa33983fbe

**Comment by jrennstich** [comment]
> You'll then need to install your forked version because `komaletter` doesn't allow to provide a new template

@cderv - thank you soooo much for your great help! I am terribly sorry to bother you further: how do I install that forked version? I am using a Mac, MacOS 10.15.1 (19B88)). I hope it's just a Terminal command, but I wouldn't really know how to install a forked and adapted version of that file.

**Comment by cderv** [comment]
I just pushed a PR into this package. You should now try
```r
remotes::install_github("rnuske/komaletter#8")
```

this should install the last dev version from the PR. 

Please test this is working and comment in the PR.

**Comment by rnuske** [comment]
Thanks for reporting @jrennstich  and solving @cderv this issue. Merged the pull request and will submit a minor update to CRAN.
